language: android
before_install:
- rm -f local.properties
- cp .project .classpath two-way-gridview/lib/
- "$ANDROID_HOME/tools/android update project --path two-way-gridview/lib/ -t android-17"
- "$ANDROID_HOME/tools/android update project --path ./ -n PosterPlayer -t android-17
  -s"
- openssl aes-256-cbc -k "$ENCKEY" -in signkit.tgz.enc -d -a -out signkit.tgz
- tar xzf signkit.tgz
script:
- ant release -propertyfile $(pwd)/monami-ya-android.properties
deploy:
  provider: releases
  api_key:
    secure: f0gXVN3OD9xN/CGtEypf9nHKL/cY58A4UylOTjqS5XdHRQNUREpEYykqP9JxuZH067DaWvH+/Sq5uB0fBMsqSEVmyV6ShaB18X8g681vLMuBsRGUnS/KRBxWhQ8GHSG8aDlf/KEuK6J69HAug6nPaZr5Hf/KfnuEy7OnIlOyNF0=
  file: bin/PosterPlayer-release.apk
  skip_cleanup: true
  on:
    repo: movsign/PosterPlayer
    tags: true
    all_branches: true
env:
  global:
    secure: NQ0FHccSsgrFpPw8i6QZp7aKZplqm1PEVY6RE0l0OMA1JmB2177Ozil2Hf5ZefnY4xNYnMZexXgiCdN30nYYk7QkZ/I6O7fGb18zK7W7RMmhG4fbkqPyuE8ODolD8nhTXGjdVZCoOq22SAq/L19otaUGQuDa/kByxfucTuIZQaY=
